<html><head><script id="wayback-guard">window.open=function(u,t){if(!u)return null;try{if(t&&t!=='_blank'&&t!=='_new'){var w=(t==='_self'||t==='_top'||t==='_parent')?window[t]:(window.parent&&window.parent.frames[t]);if(w){w.location=u;return w}}}catch(e){}return null};window.alert=function(){};window.confirm=function(){return false};window.prompt=function(){return null};</script><meta charset="utf-8"><title>File List</title>
<style id="print-size">@media print { @page { size: 176mm 240mm; } }</style><link id="dead-links-css" rel="stylesheet" href="/sites/_wayback/dead-links.css"><script id="dead-links-js" src="/sites/_wayback/dead-links.js"></script></head>
<body bgcolor="#C0C0C0" text="#000000" data-wayback-url="https://web.archive.org/web/20020815104837id_/http://www.palestinehistory.com:80/cgi-bin/websearch/websearch.pl">
<center>
<a href="/sites/palestinehistory.com/index.html" target="_top"><img src="/sites/palestinehistory.com/image/palst.gif" width="520" height="100" border="0" alt="Palestine - Home of History"></a></center>
<br>
<center><font face="Verdana, Arial, Helvetica, sans-serif" size="4"><div align="center"><b>Palestine - Home of history search results</b></div></font></center><br>
<pre>---------------------------------------------
The following directories are to be searched:
---------------------------------------------

For HTML files only:

http://www.palestinehistory.com/
http://www.palestinehistory.com/aqsa/
http://www.palestinehistory.com/intifada/
http://www.palestinehistory.com/text/

For all text files:

No directories!

-----------------------------------------------
The following files are included in the search:
-----------------------------------------------

http://www.palestinehistory.com/401.html
http://www.palestinehistory.com/403.html
http://www.palestinehistory.com/404.htm
http://www.palestinehistory.com/404.html
http://www.palestinehistory.com/500.html
http://www.palestinehistory.com/about.htm
http://www.palestinehistory.com/addcom1.html
http://www.palestinehistory.com/addcom2.html
http://www.palestinehistory.com/addguest.html
http://www.palestinehistory.com/addpet1.html
http://www.palestinehistory.com/addpet2.html
http://www.palestinehistory.com/altindex.html
http://www.palestinehistory.com/anthem.htm
http://www.palestinehistory.com/aqsa/about.htm
http://www.palestinehistory.com/aqsa/contact.htm
http://www.palestinehistory.com/aqsa/esam.htm
http://www.palestinehistory.com/aqsa/idx.htm
http://www.palestinehistory.com/aqsa/index.html
http://www.palestinehistory.com/aqsa/map.htm
http://www.palestinehistory.com/aqsa/site01.htm
http://www.palestinehistory.com/aqsa/site012.htm
http://www.palestinehistory.com/aqsa/site013.htm
http://www.palestinehistory.com/aqsa/site014.htm
http://www.palestinehistory.com/aqsa/site015.htm
http://www.palestinehistory.com/aqsa/site016.htm
http://www.palestinehistory.com/aqsa/site02.htm
http://www.palestinehistory.com/aqsa/site022.htm
http://www.palestinehistory.com/aqsa/site023.htm
http://www.palestinehistory.com/aqsa/site024.htm
http://www.palestinehistory.com/aqsa/site025.htm
http://www.palestinehistory.com/aqsa/site026.htm
http://www.palestinehistory.com/aqsa/site027.htm
http://www.palestinehistory.com/aqsa/site03.htm
http://www.palestinehistory.com/aqsa/site04.htm
http://www.palestinehistory.com/aqsa/site042.htm
http://www.palestinehistory.com/aqsa/site05.htm
http://www.palestinehistory.com/aqsa/site052.htm
http://www.palestinehistory.com/aqsa/site06.htm
http://www.palestinehistory.com/aqsa/site07.htm
http://www.palestinehistory.com/aqsa/site08.htm
http://www.palestinehistory.com/aqsa/site09.htm
http://www.palestinehistory.com/aqsa/site10.htm
http://www.palestinehistory.com/aqsa/site11.htm
http://www.palestinehistory.com/aqsa/site12.htm
http://www.palestinehistory.com/aqsa/site13.htm
http://www.palestinehistory.com/aqsa/site14.htm
http://www.palestinehistory.com/aqsa/site15.htm
http://www.palestinehistory.com/aqsa/site16.htm
http://www.palestinehistory.com/aqsa/site17.htm
http://www.palestinehistory.com/aqsa/site18.htm
http://www.palestinehistory.com/aqsa/site19.htm
http://www.palestinehistory.com/aqsa/site20.htm
http://www.palestinehistory.com/aqsa/site21.htm
http://www.palestinehistory.com/aqsa/site22.htm
http://www.palestinehistory.com/aqsa/site23.htm
http://www.palestinehistory.com/aqsa/site24.htm
http://www.palestinehistory.com/aqsa/site25.htm
http://www.palestinehistory.com/aqsa/site26.htm
http://www.palestinehistory.com/aqsa/site27.htm
http://www.palestinehistory.com/aqsa/site28.htm
http://www.palestinehistory.com/aqsa/site29.htm
http://www.palestinehistory.com/aqsa/site30.htm
http://www.palestinehistory.com/aqsa/site31.htm
http://www.palestinehistory.com/aqsa/site32.htm
http://www.palestinehistory.com/aqsa/site33.htm
http://www.palestinehistory.com/aqsa/site34.htm
http://www.palestinehistory.com/aqsa/site35.htm
http://www.palestinehistory.com/aqsa/site36.htm
http://www.palestinehistory.com/aqsa/site37.htm
http://www.palestinehistory.com/aqsa/site38.htm
http://www.palestinehistory.com/aqsa/site39.htm
http://www.palestinehistory.com/aqsa/site40.htm
http://www.palestinehistory.com/aqsa/site41.htm
http://www.palestinehistory.com/aqsa/site412.htm
http://www.palestinehistory.com/aqsa/site42.htm
http://www.palestinehistory.com/aqsa/site43.htm
http://www.palestinehistory.com/aqsa/site44.htm
http://www.palestinehistory.com/aqsa/site45.htm
http://www.palestinehistory.com/aqsa/thankyou.htm
http://www.palestinehistory.com/aqsa/title.htm
http://www.palestinehistory.com/articl00.htm
http://www.palestinehistory.com/articl01.htm
http://www.palestinehistory.com/articl02.htm
http://www.palestinehistory.com/articl03.htm
http://www.palestinehistory.com/articl04.htm
http://www.palestinehistory.com/articl05.htm
http://www.palestinehistory.com/articl06.htm
http://www.palestinehistory.com/articl07.htm
http://www.palestinehistory.com/articl08.htm
http://www.palestinehistory.com/articl09.htm
http://www.palestinehistory.com/articl10.htm
http://www.palestinehistory.com/articl11.htm
http://www.palestinehistory.com/articl12.htm
http://www.palestinehistory.com/articl13.htm
http://www.palestinehistory.com/articl14.htm
http://www.palestinehistory.com/articl15.htm
http://www.palestinehistory.com/articl16.htm
http://www.palestinehistory.com/articl17.htm
http://www.palestinehistory.com/articl18.htm
http://www.palestinehistory.com/articl19.htm
http://www.palestinehistory.com/articl20.htm
http://www.palestinehistory.com/articl21.htm
http://www.palestinehistory.com/articl22.htm
http://www.palestinehistory.com/articl23.htm
http://www.palestinehistory.com/articl24.htm
http://www.palestinehistory.com/articl25.htm
http://www.palestinehistory.com/articl26.htm
http://www.palestinehistory.com/articl27.htm
http://www.palestinehistory.com/articl28.htm
http://www.palestinehistory.com/articl29.htm
http://www.palestinehistory.com/articl30.htm
http://www.palestinehistory.com/articl31.htm
http://www.palestinehistory.com/articl32.htm
http://www.palestinehistory.com/articl33.htm
http://www.palestinehistory.com/articl34.htm
http://www.palestinehistory.com/articl35.htm
http://www.palestinehistory.com/articl36.htm
http://www.palestinehistory.com/articl37.htm
http://www.palestinehistory.com/articl38.htm
http://www.palestinehistory.com/articl39.htm
http://www.palestinehistory.com/articl40.htm
http://www.palestinehistory.com/articl41.htm
http://www.palestinehistory.com/articl42.htm
http://www.palestinehistory.com/articl43.htm
http://www.palestinehistory.com/articl44.htm
http://www.palestinehistory.com/articl45.htm
http://www.palestinehistory.com/articl46.htm
http://www.palestinehistory.com/articl47.htm
http://www.palestinehistory.com/articl48.htm
http://www.palestinehistory.com/betlhm.htm
http://www.palestinehistory.com/bl.htm
http://www.palestinehistory.com/blemail.htm
http://www.palestinehistory.com/blines.htm
http://www.palestinehistory.com/blinesm.htm
http://www.palestinehistory.com/blinest.htm
http://www.palestinehistory.com/cal1996.htm
http://www.palestinehistory.com/cal1997.htm
http://www.palestinehistory.com/cal1998.htm
http://www.palestinehistory.com/cal1999.htm
http://www.palestinehistory.com/cal2000.htm
http://www.palestinehistory.com/cal2001.htm
http://www.palestinehistory.com/calen00.htm
http://www.palestinehistory.com/calen01.htm
http://www.palestinehistory.com/calen96.htm
http://www.palestinehistory.com/calen97.htm
http://www.palestinehistory.com/calen98.htm
http://www.palestinehistory.com/calen99.htm
http://www.palestinehistory.com/calfrm00.htm
http://www.palestinehistory.com/calfrm01.htm
http://www.palestinehistory.com/calfrm96.htm
http://www.palestinehistory.com/calfrm97.htm
http://www.palestinehistory.com/calfrm98.htm
http://www.palestinehistory.com/calfrm99.htm
http://www.palestinehistory.com/camp.htm
http://www.palestinehistory.com/campgaza.htm
http://www.palestinehistory.com/campwb.htm
http://www.palestinehistory.com/cities.htm
http://www.palestinehistory.com/comlog.html
http://www.palestinehistory.com/comments.html
http://www.palestinehistory.com/comments1.html
http://www.palestinehistory.com/comments2.html
http://www.palestinehistory.com/comments3.html
http://www.palestinehistory.com/contact.htm
http://www.palestinehistory.com/doc01.htm
http://www.palestinehistory.com/doc02.htm
http://www.palestinehistory.com/doc03.htm
http://www.palestinehistory.com/doc04.htm
http://www.palestinehistory.com/doc05.htm
http://www.palestinehistory.com/doc06.htm
http://www.palestinehistory.com/doc07.htm
http://www.palestinehistory.com/doc08.htm
http://www.palestinehistory.com/doc09.htm
http://www.palestinehistory.com/doc10.htm
http://www.palestinehistory.com/doc11.htm
http://www.palestinehistory.com/doc12.htm
http://www.palestinehistory.com/doc13.htm
http://www.palestinehistory.com/doc14.htm
http://www.palestinehistory.com/doc15.htm
http://www.palestinehistory.com/doc16.htm
http://www.palestinehistory.com/doc17.htm
http://www.palestinehistory.com/doc18.htm
http://www.palestinehistory.com/doc19.htm
http://www.palestinehistory.com/document.htm
http://www.palestinehistory.com/esam.htm
http://www.palestinehistory.com/faq.htm
http://www.palestinehistory.com/filelist.htm
http://www.palestinehistory.com/flash.htm
http://www.palestinehistory.com/formmailtest.html
http://www.palestinehistory.com/galjers.htm
http://www.palestinehistory.com/galmans.htm
http://www.palestinehistory.com/galmaps.htm
http://www.palestinehistory.com/galplace.htm
http://www.palestinehistory.com/gaza.htm
http://www.palestinehistory.com/gazacity.htm
http://www.palestinehistory.com/guest1.htm
http://www.palestinehistory.com/guest10.html
http://www.palestinehistory.com/guest2.htm
http://www.palestinehistory.com/guest3.htm
http://www.palestinehistory.com/guest4.htm
http://www.palestinehistory.com/guest5.html
http://www.palestinehistory.com/guest6.html
http://www.palestinehistory.com/guest7.html
http://www.palestinehistory.com/guest8.html
http://www.palestinehistory.com/guest9.html
http://www.palestinehistory.com/guestbook.html
http://www.palestinehistory.com/guestlog.html
http://www.palestinehistory.com/hebron.htm
http://www.palestinehistory.com/history.htm
http://www.palestinehistory.com/hsitemap.htm
http://www.palestinehistory.com/hsites.htm
http://www.palestinehistory.com/hsitetxt.htm
http://www.palestinehistory.com/index.html
http://www.palestinehistory.com/index1.html
http://www.palestinehistory.com/intbio.htm
http://www.palestinehistory.com/intbio01.htm
http://www.palestinehistory.com/intbio02.htm
http://www.palestinehistory.com/intbio03.htm
http://www.palestinehistory.com/intbio04.htm
http://www.palestinehistory.com/intbio05.htm
http://www.palestinehistory.com/intbio06.htm
http://www.palestinehistory.com/intbio07.htm
http://www.palestinehistory.com/intbio08.htm
http://www.palestinehistory.com/intbio09.htm
http://www.palestinehistory.com/intbio10.htm
http://www.palestinehistory.com/intbio11.htm
http://www.palestinehistory.com/intbio12.htm
http://www.palestinehistory.com/intbio13.htm
http://www.palestinehistory.com/intbio14.htm
http://www.palestinehistory.com/intbio15.htm
http://www.palestinehistory.com/intbio16.htm
http://www.palestinehistory.com/intbio17.htm
http://www.palestinehistory.com/intbiom.htm
http://www.palestinehistory.com/intbiot.htm
http://www.palestinehistory.com/intifada/cal.htm
http://www.palestinehistory.com/intifada/day01.htm
http://www.palestinehistory.com/intifada/day02.htm
http://www.palestinehistory.com/intifada/day03.htm
http://www.palestinehistory.com/intifada/day04.htm
http://www.palestinehistory.com/intifada/day05.htm
http://www.palestinehistory.com/intifada/day06.htm
http://www.palestinehistory.com/intifada/day07.htm
http://www.palestinehistory.com/intifada/day08.htm
http://www.palestinehistory.com/intifada/day09.htm
http://www.palestinehistory.com/intifada/day10.htm
http://www.palestinehistory.com/intifada/day11.htm
http://www.palestinehistory.com/intifada/day12.htm
http://www.palestinehistory.com/intifada/day13.htm
http://www.palestinehistory.com/intifada/day14.htm
http://www.palestinehistory.com/intifada/day15.htm
http://www.palestinehistory.com/intifada/day16.htm
http://www.palestinehistory.com/intifada/day17.htm
http://www.palestinehistory.com/intifada/day18.htm
http://www.palestinehistory.com/intifada/day19.htm
http://www.palestinehistory.com/intifada/day20.htm
http://www.palestinehistory.com/intifada/day21.htm
http://www.palestinehistory.com/intifada/day22.htm
http://www.palestinehistory.com/intifada/day23.htm
http://www.palestinehistory.com/intifada/day24.htm
http://www.palestinehistory.com/intifada/day25.htm
http://www.palestinehistory.com/intifada/day26.htm
http://www.palestinehistory.com/intifada/day27.htm
http://www.palestinehistory.com/intifada/day28.htm
http://www.palestinehistory.com/intifada/day29.htm
http://www.palestinehistory.com/intifada/day30.htm
http://www.palestinehistory.com/intifada/day31.htm
http://www.palestinehistory.com/intifada/day32.htm
http://www.palestinehistory.com/intifada/day33.htm
http://www.palestinehistory.com/intifada/day34.htm
http://www.palestinehistory.com/intifada/day35.htm
http://www.palestinehistory.com/intifada/day36.htm
http://www.palestinehistory.com/intifada/day37.htm
http://www.palestinehistory.com/intifada/day38.htm
http://www.palestinehistory.com/intifada/day39.htm
http://www.palestinehistory.com/intifada/day40.htm
http://www.palestinehistory.com/intifada/day41.htm
http://www.palestinehistory.com/intifada/day42.htm
http://www.palestinehistory.com/intifada/day43.htm
http://www.palestinehistory.com/intifada/day44.htm
http://www.palestinehistory.com/intifada/day45.htm
http://www.palestinehistory.com/intifada/day46.htm
http://www.palestinehistory.com/intifada/day47.htm
http://www.palestinehistory.com/intifada/day48.htm
http://www.palestinehistory.com/intifada/day49.htm
http://www.palestinehistory.com/intifada/day50.htm
http://www.palestinehistory.com/intifada/day51.htm
http://www.palestinehistory.com/intifada/day52.htm
http://www.palestinehistory.com/intifada/day53.htm
http://www.palestinehistory.com/intifada/day54.htm
http://www.palestinehistory.com/intifada/day55.htm
http://www.palestinehistory.com/intifada/day56.htm
http://www.palestinehistory.com/intifada/day57.htm
http://www.palestinehistory.com/intifada/day58.htm
http://www.palestinehistory.com/intifada/day59.htm
http://www.palestinehistory.com/intifada/day60.htm
http://www.palestinehistory.com/intifada/day61.htm
http://www.palestinehistory.com/intifada/day62.htm
http://www.palestinehistory.com/intifada/day63.htm
http://www.palestinehistory.com/intifada/day64.htm
http://www.palestinehistory.com/intifada/index.html
http://www.palestinehistory.com/intifada/judah.htm
http://www.palestinehistory.com/intifada/mail.htm
http://www.palestinehistory.com/intifada/martyrs.htm
http://www.palestinehistory.com/intifada/moayad.htm
http://www.palestinehistory.com/intifada/mohd.htm
http://www.palestinehistory.com/intifada/sami.htm
http://www.palestinehistory.com/intifada/title.htm
http://www.palestinehistory.com/intifada/title1.htm
http://www.palestinehistory.com/intifada/title10.htm
http://www.palestinehistory.com/intifada/title2.htm
http://www.palestinehistory.com/intifada/title3.htm
http://www.palestinehistory.com/intifada/title4.htm
http://www.palestinehistory.com/intifada/title5.htm
http://www.palestinehistory.com/intifada/title6.htm
http://www.palestinehistory.com/intifada/title7.htm
http://www.palestinehistory.com/intifada/title8.htm
http://www.palestinehistory.com/intifada/title9.htm
http://www.palestinehistory.com/intifada/wael.htm
http://www.palestinehistory.com/intifada/week01.htm
http://www.palestinehistory.com/intifada/week02.htm
http://www.palestinehistory.com/intifada/week03.htm
http://www.palestinehistory.com/intifada/week04.htm
http://www.palestinehistory.com/intifada/week05.htm
http://www.palestinehistory.com/intifada/week06.htm
http://www.palestinehistory.com/intifada/week07.htm
http://www.palestinehistory.com/intifada/week08.htm
http://www.palestinehistory.com/intifada/week09.htm
http://www.palestinehistory.com/israel.htm
http://www.palestinehistory.com/isrbio.htm
http://www.palestinehistory.com/isrbio01.htm
http://www.palestinehistory.com/isrbio02.htm
http://www.palestinehistory.com/isrbio03.htm
http://www.palestinehistory.com/isrbio04.htm
http://www.palestinehistory.com/isrbio05.htm
http://www.palestinehistory.com/isrbio06.htm
http://www.palestinehistory.com/isrbio07.htm
http://www.palestinehistory.com/isrbio08.htm
http://www.palestinehistory.com/isrbio09.htm
http://www.palestinehistory.com/isrbio10.htm
http://www.palestinehistory.com/isrbio11.htm
http://www.palestinehistory.com/isrbio12.htm
http://www.palestinehistory.com/isrbio13.htm
http://www.palestinehistory.com/isrbio14.htm
http://www.palestinehistory.com/isrbio15.htm
http://www.palestinehistory.com/isrbio16.htm
http://www.palestinehistory.com/isrbio17.htm
http://www.palestinehistory.com/isrbio18.htm
http://www.palestinehistory.com/isrbio19.htm
http://www.palestinehistory.com/isrbio20.htm
http://www.palestinehistory.com/isrbiom.htm
http://www.palestinehistory.com/isrbiot.htm
http://www.palestinehistory.com/isrlorg.htm
http://www.palestinehistory.com/jerico.htm
http://www.palestinehistory.com/jurslm.htm
http://www.palestinehistory.com/links.htm
http://www.palestinehistory.com/mailcamp1.htm
http://www.palestinehistory.com/mailcamp2.htm
http://www.palestinehistory.com/map.htm
http://www.palestinehistory.com/mapmail.htm
http://www.palestinehistory.com/mapmain.htm
http://www.palestinehistory.com/mass01.htm
http://www.palestinehistory.com/mass02.htm
http://www.palestinehistory.com/mass03.htm
http://www.palestinehistory.com/mass04.htm
http://www.palestinehistory.com/mass05.htm
http://www.palestinehistory.com/mass06.htm
http://www.palestinehistory.com/mass07.htm
http://www.palestinehistory.com/mass08.htm
http://www.palestinehistory.com/massacre.htm
http://www.palestinehistory.com/nabulus.htm
http://www.palestinehistory.com/news.htm
http://www.palestinehistory.com/oldcity.htm
http://www.palestinehistory.com/oldcmenu.htm
http://www.palestinehistory.com/oldctext.htm
http://www.palestinehistory.com/oldimg01.htm
http://www.palestinehistory.com/oldimg02.htm
http://www.palestinehistory.com/oldimg03.htm
http://www.palestinehistory.com/oldimg04.htm
http://www.palestinehistory.com/oldimg05.htm
http://www.palestinehistory.com/oldimg06.htm
http://www.palestinehistory.com/oldimg07.htm
http://www.palestinehistory.com/oldimg08.htm
http://www.palestinehistory.com/oldimg09.htm
http://www.palestinehistory.com/oldimg10.htm
http://www.palestinehistory.com/oldimg12.htm
http://www.palestinehistory.com/oldimg13.htm
http://www.palestinehistory.com/oldimg14.htm
http://www.palestinehistory.com/oldimg15.htm
http://www.palestinehistory.com/oldimg16.htm
http://www.palestinehistory.com/oldimg17.htm
http://www.palestinehistory.com/oldimg18.htm
http://www.palestinehistory.com/oldimg19.htm
http://www.palestinehistory.com/oldimg20.htm
http://www.palestinehistory.com/oldimg21.htm
http://www.palestinehistory.com/oldimg22.htm
http://www.palestinehistory.com/oldimg23.htm
http://www.palestinehistory.com/oldimg24.htm
http://www.palestinehistory.com/oldimg25.htm
http://www.palestinehistory.com/oldimg26.htm
http://www.palestinehistory.com/oldimg27.htm
http://www.palestinehistory.com/oldimg28.htm
http://www.palestinehistory.com/oldimg29.htm
http://www.palestinehistory.com/oldimg30.htm
http://www.palestinehistory.com/oldimg31.htm
http://www.palestinehistory.com/oldimg32.htm
http://www.palestinehistory.com/oldimg33.htm
http://www.palestinehistory.com/oldimg34.htm
http://www.palestinehistory.com/oldimg35.htm
http://www.palestinehistory.com/oldimg36.htm
http://www.palestinehistory.com/oldimg38.htm
http://www.palestinehistory.com/oldimg39.htm
http://www.palestinehistory.com/oldimg40.htm
http://www.palestinehistory.com/oldimg41.htm
http://www.palestinehistory.com/oldimg42.htm
http://www.palestinehistory.com/oldimg43.htm
http://www.palestinehistory.com/oldimg44.htm
http://www.palestinehistory.com/oldimg45.htm
http://www.palestinehistory.com/oldimg46.htm
http://www.palestinehistory.com/others.htm
http://www.palestinehistory.com/palbio.htm
http://www.palestinehistory.com/palbio01.htm
http://www.palestinehistory.com/palbio02.htm
http://www.palestinehistory.com/palbio03.htm
http://www.palestinehistory.com/palbio04.htm
http://www.palestinehistory.com/palbio05.htm
http://www.palestinehistory.com/palbio06.htm
http://www.palestinehistory.com/palbio07.htm
http://www.palestinehistory.com/palbio08.htm
http://www.palestinehistory.com/palbio09.htm
http://www.palestinehistory.com/palbio10.htm
http://www.palestinehistory.com/palbio11.htm
http://www.palestinehistory.com/palbio12.htm
http://www.palestinehistory.com/palbio13.htm
http://www.palestinehistory.com/palbio14.htm
http://www.palestinehistory.com/palbio15.htm
http://www.palestinehistory.com/palbio16.htm
http://www.palestinehistory.com/palbio17.htm
http://www.palestinehistory.com/palbio18.htm
http://www.palestinehistory.com/palbio19.htm
http://www.palestinehistory.com/palbio20.htm
http://www.palestinehistory.com/palbio21.htm
http://www.palestinehistory.com/palbio22.htm
http://www.palestinehistory.com/palbio23.htm
http://www.palestinehistory.com/palbio24.htm
http://www.palestinehistory.com/palbio25.htm
http://www.palestinehistory.com/palbio26.htm
http://www.palestinehistory.com/palbio27.htm
http://www.palestinehistory.com/palbio28.htm
http://www.palestinehistory.com/palbio29.htm
http://www.palestinehistory.com/palbiom.htm
http://www.palestinehistory.com/palbiot.htm
http://www.palestinehistory.com/palpet.html
http://www.palestinehistory.com/palpet1.html
http://www.palestinehistory.com/palpet2.html
http://www.palestinehistory.com/palpet3.html
http://www.palestinehistory.com/palsorg.htm
http://www.palestinehistory.com/palst.htm
http://www.palestinehistory.com/palstate.htm
http://www.palestinehistory.com/petition.htm
http://www.palestinehistory.com/petlog.html
http://www.palestinehistory.com/ptime.htm
http://www.palestinehistory.com/ptline.htm
http://www.palestinehistory.com/ptmail.htm
http://www.palestinehistory.com/ptmenu.htm
http://www.palestinehistory.com/pttext.htm
http://www.palestinehistory.com/pttext01.htm
http://www.palestinehistory.com/pttext02.htm
http://www.palestinehistory.com/pttext03.htm
http://www.palestinehistory.com/pttext04.htm
http://www.palestinehistory.com/pttext05.htm
http://www.palestinehistory.com/pttext06.htm
http://www.palestinehistory.com/pttext07.htm
http://www.palestinehistory.com/pttext08.htm
http://www.palestinehistory.com/pttext09.htm
http://www.palestinehistory.com/pttext10.htm
http://www.palestinehistory.com/pttext11.htm
http://www.palestinehistory.com/pttext12.htm
http://www.palestinehistory.com/pttext13.htm
http://www.palestinehistory.com/pttext14.htm
http://www.palestinehistory.com/pttext15.htm
http://www.palestinehistory.com/pttext16.htm
http://www.palestinehistory.com/pttext17.htm
http://www.palestinehistory.com/pttext18.htm
http://www.palestinehistory.com/pttext19.htm
http://www.palestinehistory.com/pttext20.htm
http://www.palestinehistory.com/pttext21.htm
http://www.palestinehistory.com/pttext22.htm
http://www.palestinehistory.com/pttext23.htm
http://www.palestinehistory.com/pttext24.htm
http://www.palestinehistory.com/pttext25.htm
http://www.palestinehistory.com/pttext26.htm
http://www.palestinehistory.com/pttext27.htm
http://www.palestinehistory.com/pttext28.htm
http://www.palestinehistory.com/pttext29.htm
http://www.palestinehistory.com/pttext30.htm
http://www.palestinehistory.com/pttext31.htm
http://www.palestinehistory.com/pttext32.htm
http://www.palestinehistory.com/pttext33.htm
http://www.palestinehistory.com/pttext34.htm
http://www.palestinehistory.com/pttext35.htm
http://www.palestinehistory.com/pttext36.htm
http://www.palestinehistory.com/pttext37.htm
http://www.palestinehistory.com/pttext38.htm
http://www.palestinehistory.com/pttext39.htm
http://www.palestinehistory.com/pttext40.htm
http://www.palestinehistory.com/pttext41.htm
http://www.palestinehistory.com/pttext42.htm
http://www.palestinehistory.com/pttext43.htm
http://www.palestinehistory.com/pttext44.htm
http://www.palestinehistory.com/pttext45.htm
http://www.palestinehistory.com/pttext46.htm
http://www.palestinehistory.com/pttext47.htm
http://www.palestinehistory.com/pttext48.htm
http://www.palestinehistory.com/pttext49.htm
http://www.palestinehistory.com/pttext50.htm
http://www.palestinehistory.com/pttext51.htm
http://www.palestinehistory.com/pttext52.htm
http://www.palestinehistory.com/pttext53.htm
http://www.palestinehistory.com/pttext54.htm
http://www.palestinehistory.com/pttext55.htm
http://www.palestinehistory.com/pttext56.htm
http://www.palestinehistory.com/pttext57.htm
http://www.palestinehistory.com/qtime.htm
http://www.palestinehistory.com/qtimemap.htm
http://www.palestinehistory.com/qtimetxt.htm
http://www.palestinehistory.com/ramalh.htm
http://www.palestinehistory.com/recomend.htm
http://www.palestinehistory.com/ref1948.htm
http://www.palestinehistory.com/ref1967.htm
http://www.palestinehistory.com/refcamps.htm
http://www.palestinehistory.com/refemail.htm
http://www.palestinehistory.com/reftext.htm
http://www.palestinehistory.com/reftitle.htm
http://www.palestinehistory.com/reftoday.htm
http://www.palestinehistory.com/refugee.htm
http://www.palestinehistory.com/search.htm
http://www.palestinehistory.com/simages.htm
http://www.palestinehistory.com/simagesm.htm
http://www.palestinehistory.com/simagest.htm
http://www.palestinehistory.com/sitehist.htm
http://www.palestinehistory.com/siteindx.htm
http://www.palestinehistory.com/sitemap.htm
http://www.palestinehistory.com/ss.htm
http://www.palestinehistory.com/ssmail.htm
http://www.palestinehistory.com/ssmain.htm
http://www.palestinehistory.com/ssmenu.htm
http://www.palestinehistory.com/ssmenuj.htm
http://www.palestinehistory.com/ssmenus.htm
http://www.palestinehistory.com/sstitle.htm
http://www.palestinehistory.com/survey.htm
http://www.palestinehistory.com/survey1.htm
http://www.palestinehistory.com/survey2.htm
http://www.palestinehistory.com/survey3.htm
http://www.palestinehistory.com/text/anthem.htm
http://www.palestinehistory.com/text/betlhm.htm
http://www.palestinehistory.com/text/cal1996.htm
http://www.palestinehistory.com/text/cal1997.htm
http://www.palestinehistory.com/text/cal1998.htm
http://www.palestinehistory.com/text/cal1999.htm
http://www.palestinehistory.com/text/cal2000.htm
http://www.palestinehistory.com/text/cal2001.htm
http://www.palestinehistory.com/text/cities.htm
http://www.palestinehistory.com/text/contact.htm
http://www.palestinehistory.com/text/doc01.htm
http://www.palestinehistory.com/text/doc02.htm
http://www.palestinehistory.com/text/doc03.htm
http://www.palestinehistory.com/text/doc04.htm
http://www.palestinehistory.com/text/doc05.htm
http://www.palestinehistory.com/text/doc06.htm
http://www.palestinehistory.com/text/doc07.htm
http://www.palestinehistory.com/text/doc08.htm
http://www.palestinehistory.com/text/doc09.htm
http://www.palestinehistory.com/text/doc10.htm
http://www.palestinehistory.com/text/doc11.htm
http://www.palestinehistory.com/text/doc12.htm
http://www.palestinehistory.com/text/doc13.htm
http://www.palestinehistory.com/text/doc14.htm
http://www.palestinehistory.com/text/doc15.htm
http://www.palestinehistory.com/text/doc16.htm
http://www.palestinehistory.com/text/document.htm
http://www.palestinehistory.com/text/esam.htm
http://www.palestinehistory.com/text/gaza.htm
http://www.palestinehistory.com/text/gazacity.htm
http://www.palestinehistory.com/text/hebron.htm
http://www.palestinehistory.com/text/index.html
http://www.palestinehistory.com/text/israel.htm
http://www.palestinehistory.com/text/isrlorg.htm
http://www.palestinehistory.com/text/jerico.htm
http://www.palestinehistory.com/text/jurslm.htm
http://www.palestinehistory.com/text/links.htm
http://www.palestinehistory.com/text/nabulus.htm
http://www.palestinehistory.com/text/others.htm
http://www.palestinehistory.com/text/palsorg.htm
http://www.palestinehistory.com/text/palst.htm
http://www.palestinehistory.com/text/palstate.htm
http://www.palestinehistory.com/text/ramalh.htm
http://www.palestinehistory.com/text/time1900.htm
http://www.palestinehistory.com/text/time1980.htm
http://www.palestinehistory.com/text/time1996.htm
http://www.palestinehistory.com/text/time1997.htm
http://www.palestinehistory.com/text/time1998.htm
http://www.palestinehistory.com/text/time1999.htm
http://www.palestinehistory.com/text/time2000.htm
http://www.palestinehistory.com/text/time2001.htm
http://www.palestinehistory.com/text/untext.htm
http://www.palestinehistory.com/text/wartext.htm
http://www.palestinehistory.com/text/westbank.htm
http://www.palestinehistory.com/thankyou.htm
http://www.palestinehistory.com/time1900.htm
http://www.palestinehistory.com/time1980.htm
http://www.palestinehistory.com/time1996.htm
http://www.palestinehistory.com/time1997.htm
http://www.palestinehistory.com/time1998.htm
http://www.palestinehistory.com/time1999.htm
http://www.palestinehistory.com/time2000.htm
http://www.palestinehistory.com/time2001.htm
http://www.palestinehistory.com/tour.htm
http://www.palestinehistory.com/tour1.htm
http://www.palestinehistory.com/tour2.htm
http://www.palestinehistory.com/tour3.htm
http://www.palestinehistory.com/tour4.htm
http://www.palestinehistory.com/tour5.htm
http://www.palestinehistory.com/tour6.htm
http://www.palestinehistory.com/un.htm
http://www.palestinehistory.com/unmenu.htm
http://www.palestinehistory.com/untext.htm
http://www.palestinehistory.com/untitle.htm
http://www.palestinehistory.com/update.htm
http://www.palestinehistory.com/war.htm
http://www.palestinehistory.com/warmenu.htm
http://www.palestinehistory.com/wartext.htm
http://www.palestinehistory.com/wartitle.htm
http://www.palestinehistory.com/westbank.htm

Total:  632 files
        4,449 kb

Search index file successfully created.

-----------------------------------------------------------
The following files are expicitly excluded from the search:
-----------------------------------------------------------

http://www.palestinehistory.com/.htaccess
http://www.palestinehistory.com/ews

Total:  2 files

</pre>
<p></p><center><table border="" cellpadding="12"><tbody><tr><td>
<center><big><strong>Site Search</strong></big>
<form onsubmit="return false">
<p><strong>Terms for which to search:</strong>
<br><input type="TEXT" name="terms" size="60" value="">
</p><p><strong>Find:</strong> <select name="boolean"><option selected="">any terms</option><option>all terms</option></select> <strong>Display:</strong> <select name="hits"> <option>10</option><option selected="">25</option><option>50</option><option>100</option></select> hits per page
</p><p><strong>Search:</strong>
<br><input type="RADIO" name="DateRange" value="All" checked=""> All files<br><input type="RADIO" name="DateRange" value="Range"> Files posted or updated between<br><font face="Courier"><input type="TEXT" name="StartDateA" size="2"> <select name="StartDateB"><option value="0" selected="">Jan</option><option value="1">Feb</option><option value="2">Mar</option><option value="3">Apr</option><option value="4">May</option><option value="5">Jun</option><option value="6">Jul</option><option value="7">Aug</option><option value="8">Sep</option><option value="9">Oct</option><option value="10">Nov</option><option value="11">Dec</option></select> <input type="TEXT" name="StartDateC" size="4" value="2002"></font> and <font face="Courier"><input type="TEXT" name="EndDateA" size="2"> <select name="EndDateB"><option value="0" selected="">Jan</option><option value="1">Feb</option><option value="2">Mar</option><option value="3">Apr</option><option value="4">May</option><option value="5">Jun</option><option value="6">Jul</option><option value="7">Aug</option><option value="8">Sep</option><option value="9">Oct</option><option value="10">Nov</option><option value="11">Dec</option></select> <input type="TEXT" name="EndDateC" size="4" value="2002"></font>
</p><p><input type="SUBMIT" value="Search"></p></form></center>
<small>
<p align="CENTER">The search terms you input do not have to be complete words. <br>"Wash," for example, will match occurrences of wash, washer, Washington, etc.<br>Do not include asterisks or other non-alphanumeric characters in your search terms<br>unless you actually want them included (as with "C++") as part of your search.
</p></small><p align="CENTER"><small>Maintained with <strong><a href="http://awsd.com/scripts/websearch/" class="dead" aria-disabled="true">WebSearch 2.10</a></strong>.
</small>
</p></td></tr></tbody></table></center>
<p></p><center><table><tbody><tr><td><strong>Copy the following HTML code onto any pages on which you want a search form like the above:</strong></td></tr><tr><form onsubmit="return false"></form><td align="CENTER" nowrap=""><font face="Courier"><textarea cols="70" rows="10" wrap="VIRTUAL">&lt;P&gt;&lt;CENTER&gt;&lt;TABLE BORDER CELLPADDING=12&gt;&lt;TR&gt;&lt;TD&gt;
&lt;BR&gt;&lt;CENTER&gt;&lt;BIG&gt;&lt;STRONG&gt;Site Search&lt;/STRONG&gt;&lt;/BIG&gt;
&lt;BR&gt;&lt;FORM METHOD=POST ACTION="http://www.palestinehistory.com/cgi-bin/websearch/websearch.pl"&gt;
&lt;BR&gt;&lt;P&gt;&lt;STRONG&gt;Terms for which to search:&lt;/STRONG&gt;
&lt;BR&gt;&lt;BR&gt;&lt;INPUT TYPE=TEXT NAME="terms" SIZE=60 VALUE=""&gt;
&lt;BR&gt;&lt;P&gt;&lt;STRONG&gt;Find:&lt;/STRONG&gt; &lt;SELECT NAME="boolean"&gt;&lt;OPTION SELECTED&gt;any terms&lt;OPTION&gt;all terms&lt;/SELECT&gt; &lt;STRONG&gt;Display:&lt;/STRONG&gt; &lt;SELECT NAME="hits"&gt; &lt;OPTION&gt;10&lt;OPTION SELECTED&gt;25&lt;OPTION&gt;50&lt;OPTION&gt;100&lt;/SELECT&gt; hits per page
&lt;BR&gt;&lt;P&gt;&lt;STRONG&gt;Search:&lt;/STRONG&gt;
&lt;BR&gt;&lt;BR&gt;&lt;INPUT TYPE=RADIO NAME=DateRange VALUE=All CHECKED&gt; All files&lt;BR&gt;&lt;INPUT TYPE=RADIO NAME=DateRange VALUE=Range&gt; Files posted or updated between&lt;BR&gt;&lt;FONT FACE="Courier"&gt;&lt;INPUT TYPE=TEXT NAME="StartDateA" SIZE=2&gt; &lt;SELECT NAME="StartDateB"&gt;&lt;OPTION VALUE="0" SELECTED&gt;Jan&lt;OPTION VALUE="1"&gt;Feb&lt;OPTION VALUE="2"&gt;Mar&lt;OPTION VALUE="3"&gt;Apr&lt;OPTION VALUE="4"&gt;May&lt;OPTION VALUE="5"&gt;Jun&lt;OPTION VALUE="6"&gt;Jul&lt;OPTION VALUE="7"&gt;Aug&lt;OPTION VALUE="8"&gt;Sep&lt;OPTION VALUE="9"&gt;Oct&lt;OPTION VALUE="10"&gt;Nov&lt;OPTION VALUE="11"&gt;Dec&lt;/SELECT&gt; &lt;INPUT TYPE=TEXT NAME="StartDateC" SIZE=4 VALUE=2002&gt;&lt;/FONT&gt; and &lt;FONT FACE="Courier"&gt;&lt;INPUT TYPE=TEXT NAME="EndDateA" SIZE=2&gt; &lt;SELECT NAME="EndDateB"&gt;&lt;OPTION VALUE="0" SELECTED&gt;Jan&lt;OPTION VALUE="1"&gt;Feb&lt;OPTION VALUE="2"&gt;Mar&lt;OPTION VALUE="3"&gt;Apr&lt;OPTION VALUE="4"&gt;May&lt;OPTION VALUE="5"&gt;Jun&lt;OPTION VALUE="6"&gt;Jul&lt;OPTION VALUE="7"&gt;Aug&lt;OPTION VALUE="8"&gt;Sep&lt;OPTION VALUE="9"&gt;Oct&lt;OPTION VALUE="10"&gt;Nov&lt;OPTION VALUE="11"&gt;Dec&lt;/SELECT&gt; &lt;INPUT TYPE=TEXT NAME="EndDateC" SIZE=4 VALUE=2002&gt;&lt;/FONT&gt;
&lt;BR&gt;&lt;P&gt;&lt;INPUT TYPE=SUBMIT VALUE="Search"&gt;&lt;/CENTER&gt;&lt;/FORM&gt;
&lt;BR&gt;&lt;SMALL&gt;
&lt;BR&gt;&lt;P ALIGN=CENTER&gt;The search terms you input do not have to be complete words. &lt;BR&gt;&amp;quot;Wash,&amp;quot; for example, will match occurrences of wash, washer, Washington, etc.&lt;BR&gt;Do not include asterisks or other non-alphanumeric characters in your search terms&lt;BR&gt;unless you actually want them included (as with &amp;quot;C++&amp;quot;) as part of your search.
&lt;BR&gt;&lt;P ALIGN=CENTER&gt;Maintained with &lt;STRONG&gt;&lt;A HREF="http://awsd.com/scripts/websearch/"&gt;WebSearch 2.10&lt;/A&gt;&lt;/STRONG&gt;.
&lt;BR&gt;&lt;/SMALL&gt;
&lt;BR&gt;&lt;/TD&gt;&lt;/TR&gt;&lt;/TABLE&gt;&lt;/CENTER&gt;</textarea></font></td></tr></tbody></table></center>
<br>
<center>
<img src="/sites/palestinehistory.com/image/line1.gif" border="0" alt="Line"></center><br>
<center>
<font size="-1">This site created by <a href="/sites/palestinehistory.com/esam.htm">Esam Shashaa</a><br>
<a href="/sites/palestinehistory.com/contact.htm">
Contact us..</a></font></center>
<center>
<a href="/sites/palestinehistory.com/index.html" target="_top"><img src="/sites/palestinehistory.com/image/home.gif" border="1" alt="Home Page Index"></a></center>

</body></html>